name = "Turan Aymış"
print(name)
print(name.lower())
print(name.upper())
print(name.isupper())
print(name.upper().isupper())
print(len(name))
print(name[0])
print(name.index("a"))
print(name.replace("Turan","Sibel"))